# Generated by Django 4.1.5 on 2023-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='module_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=2)),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('student_section', models.CharField(max_length=1)),
                ('student_email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
