# Generated by Django 4.1.5 on 2023-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module_1',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
